### ISSUE TITLE
mix of camel case used in strings:

### ISSUE THREAD

**Issue by danmarsden** [catalyst/moodle-search_azure#2]
$string['pluginname'] = 'Azure Search';
$string['adminsettings'] = 'Plugin settings';

typically Moodle only capitalises the first word. - bit of a mix in the lang strings - should probably be consisitant?

**Comment by danmarsden** [comment]
$string['enrichsettings'] = 'Data Enrichment settings';
$string['tikahostname'] = 'Tika Hostname';

**Comment by mattporritt** [comment]
Yeah this has always annoyed me about Moodle, but I agree keeping with project standard is important. I'll push a patch with fixes.
I've only applied capitalization to the settings descriptions, not to help fields. e.g

$string['tikaport'] = 'Tika port';
$string['tikaport_help'] = 'The port of the Apache Tika endpoint';

As Apche Tika is a pronoun and should be capitalized in the description.
